# Generated by Django 5.2.7 on 2025-10-11 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('fresh', 'Fresh conversation'), ('post_compacting', 'After compacting'), ('split_point', 'Context split')], default='fresh', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'context_windows',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('beginning_message_id', models.UUIDField(blank=True, null=True)),
                ('ending_message_id', models.UUIDField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('message_count', models.IntegerField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation_files',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eras',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('message_number', models.IntegerField(blank=True, null=True)),
                ('content', models.JSONField()),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('eth_blockheight', models.BigIntegerField(blank=True, null=True)),
                ('eth_block_offset', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_backend', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('missing_from_markdown', models.BooleanField(default=False)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_creation_input_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_read_input_tokens', models.IntegerField(blank=True, null=True)),
                ('is_sidechain', models.BooleanField(default=False)),
                ('cwd', models.TextField(blank=True, null=True)),
                ('git_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('client_version', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThinkingEntity',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('is_biological_human', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'thinking entities',
                'db_table': 'thinking_entities',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='misc', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompactingAction',
            fields=[
                ('context_window', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='compacting_action', serialize=False, to='conversations.contextwindow')),
                ('ending_message_id', models.UUIDField()),
                ('compact_boundary_message_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('compact_trigger', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_compact_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contextwindow',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_windows', to='conversations.era'),
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conversations.message')),
                ('signature', models.TextField()),
            ],
            bases=('conversations.message',),
        ),
        migrations.CreateModel(
            name='ToolResult',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conversations.message')),
                ('tool_use_id', models.CharField(db_index=True, max_length=100)),
                ('is_error', models.BooleanField(default=False)),
            ],
            bases=('conversations.message',),
        ),
        migrations.CreateModel(
            name='ToolUse',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conversations.message')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_id', models.CharField(max_length=100, unique=True)),
            ],
            bases=('conversations.message',),
        ),
        migrations.AddField(
            model_name='message',
            name='context_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='conversations.contextwindow'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='contextwindow',
            name='first_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_windows', to='conversations.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', to='conversations.thinkingentity'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to='conversations.thinkingentity'),
        ),
        migrations.CreateModel(
            name='MessageTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField()),
                ('relevance', models.IntegerField(default=5, help_text='1-10 scale')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.topic')),
            ],
            options={
                'db_table': 'message_topics',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_notes', to='conversations.thinkingentity')),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='notes_content_0b9624_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session_id', 'timestamp'], name='conversatio_session_2f9f92_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='conversatio_sender__ed16aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('context_window', 'message_number')},
        ),
        migrations.AlterUniqueTogether(
            name='messagetopic',
            unique_together={('message_id', 'topic')},
        ),
    ]
