# Generated by Django 5.2.7 on 2025-10-23 03:36

from django.db import migrations, models
import django.db.models.deletion


def create_participants_from_entities(apps, schema_editor):
    """
    Create ConversationParticipant records for existing ThinkingEntity records.
    """
    ThinkingEntity = apps.get_model('conversations', 'ThinkingEntity')
    ConversationParticipant = apps.get_model('conversations', 'ConversationParticipant')

    for entity in ThinkingEntity.objects.all():
        # Determine participant type
        if entity.name == 'magent':
            participant_type = 'ai'
        elif entity.is_biological_human:
            participant_type = 'human'
        else:
            participant_type = 'ai'

        # Create ConversationParticipant with same name
        ConversationParticipant.objects.create(
            name=entity.name,
            participant_type=participant_type
        )


def link_entities_to_participants(apps, schema_editor):
    """
    Populate the conversationparticipant_ptr field for each ThinkingEntity.
    """
    ThinkingEntity = apps.get_model('conversations', 'ThinkingEntity')
    ConversationParticipant = apps.get_model('conversations', 'ConversationParticipant')

    for entity in ThinkingEntity.objects.all():
        participant = ConversationParticipant.objects.get(name=entity.name)
        entity.conversationparticipant_ptr = participant
        entity.save(update_fields=['conversationparticipant_ptr'])


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        # Step 1: Create ConversationParticipant table
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('participant_type', models.CharField(
                    choices=[('human', 'Human'), ('ai', 'AI'), ('tool', 'Tool'), ('oracle', 'Oracle'), ('system', 'System')],
                    default='human',
                    max_length=20
                )),
            ],
            options={
                'db_table': 'conversation_participants',
            },
        ),

        # Step 2: Create ConversationParticipant records
        migrations.RunPython(create_participants_from_entities, migrations.RunPython.noop),

        # Step 3: Add nullable OneToOneField to ThinkingEntity
        migrations.AddField(
            model_name='thinkingentity',
            name='conversationparticipant_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to='conversations.conversationparticipant',
                null=True,  # NULLABLE initially
                serialize=False
            ),
        ),

        # Step 4: Populate the FK field
        migrations.RunPython(link_entities_to_participants, migrations.RunPython.noop),

        # Step 5: Make the FK NOT NULL
        migrations.AlterField(
            model_name='thinkingentity',
            name='conversationparticipant_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to='conversations.conversationparticipant',
                serialize=False
            ),
        ),

        # Step 6: Remove the standalone 'name' field from ThinkingEntity
        migrations.RemoveField(
            model_name='thinkingentity',
            name='name',
        ),

        # Step 7: Make conversationparticipant_ptr the primary key
        migrations.AlterField(
            model_name='thinkingentity',
            name='conversationparticipant_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='conversations.conversationparticipant'
            ),
        ),

        # Step 8: Update Message.sender to point to ConversationParticipant
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sent_messages',
                to='conversations.conversationparticipant'
            ),
        ),

        # Step 9: Update Message.recipients to point to ConversationParticipant
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(
                related_name='received_messages',
                to='conversations.conversationparticipant'
            ),
        ),
    ]
