# Generated by Django 5.2.7 on 2025-10-15 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compactingaction',
            name='preceding_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compacting_action_after_this', to='conversations.message'),
        ),
    ]
