# Generated by Django 5.2.7 on 2025-10-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='eth_blockheight',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
