# Generated by Django 5.2.7 on 2025-10-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_add_preceding_message_to_compactingaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooluse',
            name='tool_id',
            field=models.CharField(max_length=100),
        ),
    ]
