# Generated by Django 5.2.7 on 2025-11-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('conversations', '0002_add_conversation_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawimportedcontent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='rawimportedcontent',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
