# Generated by Django 5.2.7 on 2025-10-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_note_eth_blockheight'),
    ]

    operations = [
    ]
