# Generated by Django 5.2.7 on 2025-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_tooluse_tool_id_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='apparent_duplicate',
            field=models.BooleanField(default=False, help_text='True if this message was encountered again during import with different content (likely whitespace differences)'),
        ),
    ]
