# Generated by Django 5.2.7 on 2025-10-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_add_blockheight_offset_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextwindow',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_windows', to='conversations.era'),
        ),
        migrations.AlterField(
            model_name='contextwindow',
            name='first_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_windows', to='conversations.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='context_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.contextwindow'),
        ),
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conversations.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='conversations.thinkingentity'),
        ),
        migrations.AlterField(
            model_name='note',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to='conversations.thinkingentity'),
        ),
    ]
