# Generated by Django 5.2.7 on 2025-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_alter_contextwindow_era_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_synthetic_error',
            field=models.BooleanField(default=False),
        ),
    ]
