# Generated by Django 5.2.7 on 2025-10-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_add_apparent_duplicate_field'),
    ]

    operations = [
    ]
